### ISSUE TITLE
No license 

### ISSUE THREAD

**Issue by fred-rick** [FozzieHi/Ransomware#1]
Please add a license

**Comment by FozzieHi** [comment]
I obviously did not create these samples unless you want a license for the python run file?

**Comment by fred-rick** [comment]
Yes, i am actually asking license for the python run file.

**Comment by FozzieHi** [comment]
How would I license one individual file? I get having a license file for the whole repository but I'm not sure how I'd license a specific file.

**Comment by jasonbroadie** [comment]
Yes, you can't really add license to an individual file. But the reason i mentioned 'license for the script'   is because without any open source license,  no one can use the script  legally.   
So can you please add a license file  for the whole repositor?
